name: Generate Jar

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  create-release:
    permissions: write-all
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          draft: 'false'
          prerelease: 'false'
  build-desktop:
    permissions: write-all
    name: Build Release
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.create-release.outputs.tag_name }}
          repository: '${{ github.repository }}'

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Change wrapper permissions
        run: chmod +x ./mvnw

      - name: Download Maven Wrapper
        run: ./mvnw wrapper:wrapper

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Upload Linux Jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./target/EarthSound-${{github.ref_name}}-shaded.jar
          asset_name: EarthSound-${{github.ref_name}}-shaded.jar
          asset_content_type: application/java-archive